multinet-app/multinet-api

- multinet/api/utils/swagger.py
- multinet/api/views/network.py
- multinet/api/views/table.py
- multinet/api/views/workspace.py
- multinet/settings.py
- multinet/urls.py
This does two things:
* Organizes the endpoints by operation (workspaces, tables, networks)
* Renames `s3-upload` to `upload`
> Improve Swagger Page

- multinet/api/tasks/process/csv.py
- multinet/api/tasks/process/d3_json.py
- multinet/api/tasks/process/utils.py
- multinet/api/views/upload.py
Closes #44
This PR adds a `ProcessUploadTask` class, which extends Celery's default `Task` class, to allow for automatic updating of upload statuses. Now when dispatching a task, the following occurs automatically:
1. The logger prints that the upload is being processed
2. The upload status is changed to `STARTED`
3. The task is run
4. If any exception occurs during the task execution, the upload status is changed to `FAILED`, and the error message associated is included in the `error_messages` field
5. If the task completes successfully, the upload status is changed to `FINISHED`.
> Add automatic task state handling

- multinet/api/models/table.py
- multinet/api/tests/test_table.py
- multinet/api/tests/utils.py
- multinet/api/utils/arango.py
- multinet/api/views/table.py
- setup.py
Closes #37 
This PR contains the following changes:
* Removes the returning of new/old documents when calling the row insert/delete endpoints, simply returning the number of documents inserted/deleted instead.
* Update the arango client to not timeout after 60 seconds, to allow for bulk document uploads.
* Add a `filter` parameter to the row retrieval endpoint, to allow passing in an arango document/sub-document to filter the returned documents. This is to fill a gap left by removing the returning of new documents.
Originally #37 proposed chunking the calls to `insert_many` in order to mitigate the chance of timeout. However, there are still many circumstances where that solution falls short. The solution put forth in this PR (removing timeouts in our arango client) allows for bulk …
> Update row retrieval, insertion and deletion

- multinet/api/models/workspace.py
- multinet/api/tests/test_workspace.py
- multinet/api/views/workspace.py
Fixes #65
The issue is that there are multiple `WorkspaceRole` entries which correspond to the same workspace. Because of how Postgres joins these tables during the query, the same workspace can be returned multiple times. [Here](https://stackoverflow.com/questions/35823197/why-does-q-object-return-duplicated-results) is a stackoverflow thread about this.
The solution is to use the [`distinct`](https://docs.djangoproject.com/en/3.2/ref/models/querysets/#distinct) queryset method, to eliminate these duplicates.
> Return distinct workspaces from get_queryset

- multinet/api/tests/factories.py
- multinet/api/tests/test_network.py
- multinet/api/tests/test_table.py
- multinet/api/tests/test_upload_common.py
- multinet/api/tests/test_upload_csv.py
- multinet/api/tests/test_upload_d3_json.py
- multinet/api/tests/test_workspace.py
- multinet/api/tests/utils.py
Closes #56 
This PR leverages `pytest`'s ability to parametrize tests. We can reduce the number of test functions written for our API endpoints while increasing the number of test cases to include all permission levels. 
This PR makes the following changes:
1. Use `@pytest.mark.parametrize(<args>, [<values>])` to define how arguments to test functions should change with test cases on API endpoints that require similar set ups
2. Removal of test functions made redundant by no. 1
3. Removal of now-unnecessary helper function to generate a range of workspace permissions
4. Change our factory boy factories to use `LazyAttribute` over `SubFactory` to reduce coupling between our `pytest` fixtures
> Parametrize API endpoint tests

- multinet/api/models/workspace.py
- multinet/api/tests/test_workspace.py
- multinet/api/views/serializers.py
- multinet/api/views/workspace.py
After seeing our use of #67 in https://github.com/multinet-app/multinet-client/pull/192, I realized it's cumbersome to not return the integer permission level itself from the the API, as we'll just need to reconstruct it on the client anyway. This PR amends that to return both the level itself and the associated label, returning `null` for both if they don't exist.
I think this will make the use of it much easier on the client, in particular removing the need for code like [this](https://github.com/multinet-app/multinet-client/blob/1d2aad1ad0824e67777b8dde8b57f99e6990629d/src/utils/permissions.ts#L4-L17). @naglepuff lmk what you think.
> Return both permission level and label from user permissions endpoint

- multinet/api/views/common.py
- multinet/api/views/network.py
- multinet/api/views/serializers.py
- multinet/api/views/table.py
It turns out with get requests, you can use the `query_serializer` parameter of `swagger_auto_schema`. This removes the need for us to use `manual_parameters`, and allows us to handle get request parameters in a similar way to that of put/post requests.
> Fix use of serializers in get requests

- multinet/api/tests/conftest.py
- multinet/api/tests/test_network.py
- multinet/api/views/network.py
- multinet/api/views/serializers.py
Closes #73 
This PR creates the following endpoint:
`GET /api/workspaces/{workspace}/networks/{network}/tables/`
which can be used to retrieve information about node and edge tables that make up a particular network. It accepts an optional query parameter, `type`, which can be equal to `node` or `edge`, in which case the response will only contain tables of that type.
Omitting the query parameter will return tables of both types.
This endpoint is useful for client applications such as `multimatrix`, which uses table names to generate particular AQL queries.
> Create endpoint to retrieve a network's tables

- setup.py
No, I have noticed this issue when rebuilding the django container locally, though.
This fixes the django major (and maybe minor version) to 3(.2). This stops the django containers, and presumably the heroku deployment, from using django v4.0, which our code is not compatible with. We're using some deprecated and removed functions.
We should hold off on merging any other PR until this is merged.
N/A
No
> Fix django major version to 3

- multinet/api/models/table.py
- setup.py
Depends #89
Closes #85
This chunks the upload using hints from #85. I used almost exactly the same syntax, while making sure to not use the `readonly` user. The upload runs with chunks of 5000 rows, which may be too small.
N/A
No.
> Add chunking to put_rows and delete_rows

- multinet/api/utils/arango.py
Depends on #89 
This fixes an issue I've been having on UPDB with applying filters to a query. When I would add the filters, I'd hit this memory limit.
Increasing the limit here fixes the problem. There are still issue on the main client with showing the number of nodes and the "node types". I think that we can modify the queries that run on `/nodes/?offset=0&limit=10` to reduce the memory use, since it shouldn't need to load every table to get the count.
> Increase AQL memory limit to 1GiB from 20MB

- multinet/api/tasks/upload/d3_json.py
- multinet/api/tests/test_upload_d3_json.py
This PR addresses https://github.com/multinet-app/multinet-client/issues/216, by changing the way json files are processed. It used to be the case that `nodes[*].id` and `links[*].<source|target>` were assumed to be present, failing the upload if they were missing. This has been updated, so that if these keys are missing for any node/link, that specific node/link is skipped, and not ingested into the network.
> Update D3 JSON uploader to handle missing keys

- README.md
It's very easy to not include the trailing slash in the redirect URI input, even though it's technically included here. Several people (including myself several times) have run into this issue. This adds a note to make the distinction clear.
> Add note to OAuth client setup

- multinet/api/tasks/upload/csv.py
- multinet/api/tests/test_csv_network.py
- multinet/api/views/network.py
- multinet/api/views/serializers.py
Backend change for https://github.com/multinet-app/multinet-client/pull/227
> Add new csv based network creation mode

- multinet/settings.py
No
We were getting a bunch of warnings that look like:
```
...
api.Upload: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
HINT: Configure the DEFAULT_AUTO_FIELD setting or the ApiConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
api.Workspace: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
HINT: Configure the DEFAULT_AUTO_FIELD setting or the ApiConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
...
```
Following the advice [here](https://dev.to/weplayinternet/upgrading-to-django-3-2-and-fixing-defaultautofield-warnings-5 …
> Add DEFAULT_AUTO_FIELD to silence warning on the command line

- multinet/api/tasks/upload/csv.py
- multinet/api/tests/test_csv_network.py
Closes https://github.com/multinet-app/multinet-client/issues/256
This fixes a bug in csv network creation in which edge tables rows that had no matching value in either the source or target table (i.e. there was no document that had a value matching that of the edge table in the required column) would still be blindly inserted. This would fail and cause an internal server error, since they contained a `_from` or `_to` field with a value of `null`.
> Filter out missed joins in csv network creation

- multinet/api/tasks/upload/csv.py
- multinet/api/tests/test_upload_csv.py
- multinet/api/views/serializers.py
- multinet/api/views/upload.py
There's no issue in the api for this, it's a frontend issue.
This allows for a user/frontend specified delimiter for processing csv files. This is important, since csvs are only loosely standardized. With the frontend, we can now support `,`,`;`,`\t`, etc.
N/A
No
> Add a delimiter field to the csv upload for user specification

- multinet/api/tasks/upload/csv.py
Depends #145
This batches up the inserts for uploading large tables. With this code, I managed to upload ~6.5 million rows (at a csv file size of 2.5 GB) without running out of memory.
I decided to make this PR depend on #145, since it's modifying similar code. The final commit is the only new change in this branch
N/A
> Make CSV uploader insert in batches

- multinet/api/views/serializers.py
- tox.ini
None open but allows for whitespace delimiters in CSV
This PR adds the ability to use a whitespace delimiter for CSV files.
> removed default whitespace trim for delimiter serializer

- multinet/api/views/alttxt.py
Closes none
This PR updates the alttext view so that level is an optional parameter with a default value `default`. This is necessary because the newest alttext-gen version 0.1.11 (#165) uses the `default` value to combine levels when generating alttext.
TODOs:
- [ NA ] Update relevant documentation (don't think there is any)
> Add default field for alttxt level serializer

- docker-compose.override.yml
- docker-compose.yml
- multinet/api/tasks/upload/process_single_table.py
- multinet/api/tasks/upload/utils.py
- setup.py
Closes #173 
This PR adds a string cast when pulling the column value during table upload. This is because the types are loading dynamically (ie: float, int, etc) but the processing functions are assuming string types for any input. This means that types such as float will be cast to int in the `str_to_number` function, without raising any error.
One option is to modify the `str_to_number` function, but this is not inline with the behavior of all other types.
Dataset upload for movies dataset tested locally and working as expected.
See #173 screenshots
TODOs:
> Update row processing string assumption

- setup.py
Closes none
Bumps alt-txt package version to [v0.2.8](https://github.com/visdesignlab/upset-alt-txt-gen/releases/tag/v0.2.8)
TODOs:
> Bump upset-alttxt to 0.2.8

- multinet/api/models/network.py
- multinet/api/models/table.py
- multinet/api/views/workspace.py
Closes none
This PR adds a workspace endpoint for forking, as well as adds a copy function to the table and network models.
See https://github.com/multinet-app/multinet-client/pull/308
TODOs:
> Workspace fork
